--!Type(Module)

reportPots = Event.new("reportPost")
requestPlayerState = Event.new("requestPlayerState")
requestReportNum = Event.new("requestReportNum")
requestSecret = Event.new("requestSecret")
requestStorageArrayLenght = Event.new("requestStorageArrayLenght")
requestStoragePlayerData = Event.new("requestStoragePlayerData")
newComment = Event.new("newComment")
newSecret = Event.new("newSecret")
setChat = Event.new("setChat")
setPlayerState = Event.new("setPlayerState")
setStoragePlayerData = Event.new("setStoragePlayerData")
setText = Event.new("setText")