--!Type(Module)

premadeSecrets = {
    {
        comments = {},
        id = 01,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = 'I once stole something from a supermarket to make a prank and catch a friend lying about stuff. I put THE THING:tm: in their backpack and they said it was from their cousins. I caught him lying and my only reaction was "I KNEW IT!!!!".',
    }
    --[[
    ,

    
    {
        comments = {},
        id = 02,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I liked MLP:FIM as a kid but I didn't admit it not because it was girly and I was still trying to pretend I was a boy, but because my little brother liked it and I refused to like anything he liked.",
    },
    {
        comments = {},
        id = 03,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "Not really a secret, but I got \"married\" and \"divorced\" when I was like five. I remember the girl's name but I don't remember that happening. But my mother keeps telling that to everyone. It's pretty funny ngl.",
    },
    {
        comments = {},
        id = 04,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I ***LOVE*** pineapple pizza. Like, screw it! I love it! I'm sorry, it's just DELICIOUS!!!!!!!!",
    },
    {
        comments = {},
        id = 05,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I'm 22 and I don't know how to tell my dad I'm trans.",
    },
    {
        comments = {},
        id = 06,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I'm scared of life.",
    },
    {
        comments = {},
        id = 07,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I think all of my relationships ended because I screwed up. Luckily, things with all of my exes are oki. But I am kind of sad I might never make things work with anyone.",
    },
    {
        comments = {},
        id = 08,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "My favourite moments of school and university were leaving. I love learning but I hate how those work.",
    },
    {
        comments = {},
        id = 09,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I'm 22 and I've never got drunk. I don't get people being drunk.",
    },
    {
        comments = {},
        id = 010,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "Sometimes I think I would date anyone who treats me well. But I've got few dates in my life. I'm not sure what does that mean.",
    },
    {
        comments = {},
        id = 011,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "Voujour. That's all italian I know.",
    },
    {
        comments = {},
        id = 012,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I once went to UK and GOSH the food is AWFUL. I LITERALLY ate cartonboard once and it was BETTER!!!!",
    },
    {
        comments = {},
        id = 013,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I'm secretly a furry and a brony.",
    },
    {
        comments = {},
        id = 014,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I don't get this game. Not this one as the secrets one, but Highrise. I can't get to make a single friend.",
    },
    {
        comments = {},
        id = 015,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I am french but if I tell any of my friends they'll start making french jokes around me and won't stop until I die.",
    },
    {
        comments = {},
        id = 016,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I still sleep with my childhood stuffed animal.",
    },
    {
        comments = {},
        id = 017,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a secret crush on my best friend's sibling.",
    },
    {
        comments = {},
        id = 018,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a hidden diary where I write about my day. I checked some pretty old entries and, gosh. I've been sad most of my life.",
    },
    {
        comments = {},
        id = 019,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a hidden diary where I write about my day.",
    },
    {
        comments = {},
        id = 020,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I once read my sibling's text messages out of curiosity and I regret it so much. Not because of invading their privacy, but I found out she's into... Weird stuff.",
    },
    {
        comments = {},
        id = 021,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I tried vaping once but didn't tell anyone.",
    },
    {
        comments = {},
        id = 022,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been saving money to buy something my parents took it to buy an ugly elephant figure.",
    },
    {
        comments = {},
        id = 023,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I pretend to like certain music just to fit in with my friends. I just don't wanna be left alone again...",
    },
    {
        comments = {},
        id = 024,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've told white lies about my whole life to seem cooler. At this point, I think no one knows my real self. Not even my family.",
    },
    {
        comments = {},
        id = 025,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've had doubts about my future career path, even though I tell everyone I'm certain.",
    },
    {
        comments = {},
        id = 026,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I sometimes feel overwhelmed by social media pressure and have considered deleting my accounts.",
    },
    {
        comments = {},
        id = 027,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I struggle with body image issues but don't talk about it with anyone.",
    },
    {
        comments = {},
        id = 027,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've pretended to be more experienced in relationships than I actually am.",
    },
    {
        comments = {},
        id = 028,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've skipped family events because I needed time alone, but I told them I had plans.",
    },
    {
        comments = {},
        id = 029,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've secretly taken online courses to learn about topics I'm passionate about but don't share with my friends.",
    },
    {
        comments = {},
        id = 030,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've secretly taken online courses to learn about topics I'm passionate about but don't share with my friends.",
    },
    {
        comments = {},
        id = 031,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I'm scared of growing up and the responsibilities that come with it.",
    },
    {
        comments = {},
        id = 031,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've tried alcohol at a party and regretted it later.",
    },
    {
        comments = {},
        id = 032,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a close online friend who knows more about me than some of my irl friends do.",
    },
    {
        comments = {},
        id = 033,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've lied about my feelings to avoid conflict or disappointing others.",
    },
    {
        comments = {},
        id = 034,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've had serious thoughts about changing my major but haven't told my parents.",
    },
    {
        comments = {},
        id = 035,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I sometimes feel like I'm not good enough despite my friends saying otherwise. I wish I could believe in myself.",
    },
    {
        comments = {},
        id = 036,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've struggled with anxiety and haven't told anyone about it.",
    },
    {
        comments = {},
        id = 037,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've fallen for a friend who's already in a relationship.",
    },
    {
        comments = {},
        id = 038,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I sometimes fake confidence because I'm actually VERY insecure.",
    },
    {
        comments = {},
        id = 039,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've considered taking a gap year to figure out what I truly want. I'm just kinda scared of my family's reaction... Also I kinda fear not figuring it out and just going back to nosense efforts.",
    },
    {
        comments = {},
        id = 040,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I worry that I'll never live up to my family's expectations.",
    },
    {
        comments = {},
        id = 041,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've stayed in a relationship longer than I should have out of fear of being alone.",
    },
    {
        comments = {},
        id = 042,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I sometimes feel disconnected from everyone. Even from my closest friends.",
    },
    {
        comments = {},
        id = 043,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've kept quiet about my true beliefs to avoid arguments.",
    },    
    {
        comments = {},
        id = 044,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been secretly learning a new language and am getting pretty good at it! But I'm shy to tell everyone because my environment kinda hates \"eggheads\".",
    },
    {
        comments = {},
        id = 045,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I donate to charity regularly. Lately, I've been only able to give an small amount. But I believe in a lot of small ammounts making a difference. <3",
    },
    {
        comments = {},
        id = 046,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been mentoring a younger student and it's very rewarding! It kinda makes me blush how stubborn I was to start doing it. I wish I started earlier!",
    },
    {
        comments = {},
        id = 047,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I practice mindfulness and meditation to help with stress.",
    },
    {
        comments = {},
        id = 048,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been saving up to travel to a place I've always dreamed of visiting. I've not told anyone because the place is not what anyone would expet from me.",
    },
    {
        comments = {},
        id = 049,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I write poetry and have a collection of poems I'm proud of.",
    },
    {
        comments = {},
        id = 050,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been working on a secret art project that I'm excited to share someday. It's been years since I started!",
    },
    {
        comments = {},
        id = 051,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I volunteer at a local shelter and it makes me feel more connected to my community.",
    },
    {
        comments = {},
        id = 052,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been learning to cook and it has helping me get better emotionally. It's a bit silly(?), but sometimes it feels my food's flavor shows how I feel. And feeling better makes it taste better.",
    },
    {
        comments = {},
        id = 053,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a passion for photography and I've learned so much with it. Not only about pictures, but also about history and even some math.",
    },
    {
        comments = {},
        id = 054,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I secretly enjoy classical music and sometimes go to concerts alone.",
    },
    {
        comments = {},
        id = 055,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've been working out regularly and I'm starting to like myself.",
    },
    {
        comments = {},
        id = 056,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I have a small garden that I tend to and it brings me a lot of peace.",
    },
    {
        comments = {},
        id = 057,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I read self-help books and despite their bad name, they've really helped me grow as a person.",
    },
    {
        comments = {},
        id = 058,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I've made a personal goal to compliment someone every day. Somehow it got me a partner.",
    },
    {
        comments = {},
        id = 059,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I keep a gratitude journal and it helps me stay positive.",
    },
    {
        comments = {},
        id = 060,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I finally have enough moeny to open my own business!.",
    },
    {
        comments = {},
        id = 061,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "I enjoy stargazing and sometimes spend hours watching the night sky.",
    },
    {
        comments = {},
        id = 062,
        idPlayer = 0,
        hidden = false,
        reportNum = 0,
        text = "Can we pretend that airplanes at the night sky are like shooting stars?",
    },
    --]]

}