/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/DisplayRandomSecret")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class DisplayRandomSecret : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "80bcfe772849dfd46a55731972331d8a";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Scripts UI")]
        [SerializeField] public UnityEngine.GameObject _GameManager = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _GameManager),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
                CreateSerializedProperty(_script.GetPropertyAt(4), null),
                CreateSerializedProperty(_script.GetPropertyAt(5), null),
            };
        }
    }
}

#endif
