/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class UIManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "566e29298adf1e34ea8dd5b012601315";
        public override string ScriptGUID => s_scriptGUID;

        [Header("Scripts UI")]
        [SerializeField] public UnityEngine.GameObject _UIManager = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _UIManager),
            };
        }
    }
}

#endif
